apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-service-deployment
  labels:
    app: web-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-service
  template:
    metadata:
      labels:
        app: web-service
    spec:
      containers:
        - name: web-service
          image: web-service:v1  # <-- Replace with your image
          ports:
            - containerPort: 80
